apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-service
  namespace: homework
  labels:
    app: hw-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: hw-service
  template:
    metadata:
      labels:
        app: hw-service
    spec:
      nodeSelector:
        homework: "true"
      containers:
      - name: hw-service
        image: zagretdinov/hw:0.4
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"