apiVersion: v1
kind: Pod
metadata:
  name: hw
  namespace: homework
  labels:
    app: hw
spec:
  initContainers:
  - name: init-hw
    image: alpine:latest
    volumeMounts:
    - name: app
      mountPath: /app
    command: ["/bin/sh", "-c", "mkdir /app/init && echo '<html><body><h1>Help!!! I Live!</h1></body></html>' > /app/init/index.html"]
  volumes:
    - name: app
      emptyDir: {}

  containers:
  - name: hw
    image: zagretdinov/hw:0.3
    
    imagePullPolicy: Always 
    readinessProbe:
      httpGet:
        path: /
        port: 8000
    livenessProbe:
      tcpSocket: { port: 8000 }
    startupProbe:
      httpGet:
        path: /
        port: 8000
      failureThreshold: 30
      periodSeconds: 10
    volumeMounts:
    - name: app
      mountPath: /app/homework
    lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/init/index.html"]
 
  